### ISSUE TITLE
failed:  log 

### ISSUE THREAD

**Issue by Zakspeed** [r-pufky/digikam#2]
```
......
Digikam::adjustedEnvironmentForAppImage: Adjusting environment variables for AppImage bundle
Digikam::DBinarySearch::slotAreBinariesFound: All Binaries Found :  false
Digikam::DBinaryIface::checkDirForPath: Testing  "././/sbin/mysql_install_db" ...
Digikam::adjustedEnvironmentForAppImage: Adjusting environment variables for AppImage bundle
Digikam::DBinarySearch::slotAreBinariesFound: All Binaries Found :  false
Digikam::DBinaryIface::checkDirForPath: Testing  "././/sbin/mysqld" ...
Digikam::adjustedEnvironmentForAppImage: Adjusting environment variables for AppImage bundle
Digikam::DBinarySearch::slotAreBinariesFound: All Binaries Found :  false
libEGL warning: DRI2: failed to open swrast (search paths ././/lib64/dri)
libEGL warning: DRI2: failed to open swrast (search paths ././/lib64/dri)
libEGL warning: DRI2: failed to open swrast (search paths ././/lib64/dri)
libEGL warning: DRI2: failed to open swrast (search paths ././/lib64/dri)
```

I tried:
apt install libgl1-mesa-dri

but:
debconf: delaying package configuration, since apt-utils is not installed

**Comment by r-pufky** [comment]
Please let me know what docker image you are using so I can investigate.

**Comment by Zakspeed** [comment]
My "docker-compose.yml"

```
version: "3"
services:
  digikam:
    image: rpufky/digikam:stable
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - UMASK=022
      - TZ=Europe/Madrid
      - KEEP_APP_RUNNING=1
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - ENABLE_CJK_FONT=1
    volumes:
      - ./config:/config
      - ./photolocation:/data
      - /etc/localtime:/etc/localtime:ro
```
**My host:**  Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-96-generic x86_64)
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false
