### ISSUE TITLE
Warning for locale change

### ISSUE THREAD

**Issue by sse450** [r-pufky/digikam#5]
Dear r-pufky,

I appreciate your efforts for this docker. I upgraded one of old dockers (7.0.0 Beta) to the latest today.

Upon start it gives me a warning about locale change:
![2020-09-18_11-34](https://user-images.githubusercontent.com/15627450/93576474-9ac7eb00-f9a3-11ea-9c36-81545aa7ee48.png)

I know that my filenames are all UTF-8. Don't know where "System" locale is coming from.

What should I do?

Thank you.

**Comment by r-pufky** [comment]
I'll take a look into it this weekend. Initial thought is that the base image update changed the default locale, most likely fixed by explicitly setting UTF-8 on the build.

**Comment by r-pufky** [comment]
It looks like the beta track at some point specified UTF-8 as a locale, or it was passed in your environment. Eitherway, I've updated the image so you can explicitly override the default locale (POSIX).

See updated documentation. Just add the correct locale information to your compose file and pull the updated image. the message should go away.

```yaml
services:
  digikam:
    environment:
      - "LANG=en_US.UTF-8"
      - "LANGUAGE=en_US.UTF-8"
      - "LC_ALL=en_US.UTF-8"
```

Your locale may be different from the example above, just specify the locale you typically use or use the one above.
